SELECT COUNT(*) FROM companies;
SELECT COUNT(*) FROM profitandloss;
SELECT COUNT(*) FROM balancesheet;
SELECT COUNT(*) FROM cashflow;
SELECT MIN(year), MAX(year) FROM profitandloss;
SELECT company_id,COUNT(*) AS years_available FROM profitandloss GROUP BY company_id ORDER BY years_available;
SELECT company_id,COUNT(*) AS years_available FROM profitandloss GROUP BY company_id HAVING COUNT(*) < 5;
SELECT COUNT(*) FROM companies;
SELECT COUNT(*) FROM profitandloss;
SELECT COUNT(*) FROM balancesheet;
SELECT COUNT(*) FROM cashflow;
SELECT MIN(year), MAX(year) FROM profitandloss;
SELECT company_id,MAX(sales) FROM profitandloss GROUP BY company_id ORDER BY MAX(sales) DESC LIMIT 10;
SELECT AVG(net_profit)FROM profitandloss;
SELECT AVG(assets)FROM balancesheet;
SELECT company_id,COUNT(*) FROM profitandlossasNfEienvoe GROUP BY company_id HAVING COUNT(*) < 5;
SELECT SUM(operating_cash_flow)FROM cashflow;