PRAGMA foreign_keys = ON;
CREATE TABLE companies (company_id INTEGER PRIMARY KEY,company_name TEXT,sector TEXT);
CREATE TABLE profitandloss (company_id INTEGER,year INTEGER,sales REAL,operating_profit REAL,other_income REAL,EBIT REAL,interest REAL,net_profit REAL,earnings_per_share REAL,dividend REAL,PRIMARY KEY (company_id, year),FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE balancesheet (company_id INTEGER,year INTEGER,assets REAL,liabilities REAL,equity_capital REAL,reserves REAL,borrowings REAL,investments REAL,PRIMARY KEY (company_id, year),FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE cashflow (company_id INTEGER,year INTEGER,operating_activity REAL,investing_activity REAL,financing_activity REAL,PRIMARY KEY (company_id, year),FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE financial_ratios (company_id INTEGER,year INTEGER,net_profit_margin_pct REAL,operating_profit_margin_pct REAL,return_on_equity_pct REAL,return_on_capital_employed_pct REAL,return_on_assets_pct REAL,debt_to_equity REAL,interest_coverage REAL,asset_turnover REAL,PRIMARY KEY (company_id, year),FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE analysis (company_id INTEGER,analysis TEXT,FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE documents (company_id INTEGER,document_name TEXT,FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE prosandcons (company_id INTEGER,pros TEXT,cons TEXT,FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE sectors (sector_id INTEGER PRIMARY KEY,sector_name TEXT);
CREATE TABLE stock_prices (company_id INTEGER,year INTEGER,price REAL,FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE peer_groups (company_id INTEGER,peer_company TEXT,FOREIGN KEY (company_id) REFERENCES companies(company_id));